# configs/stage2.yaml
name: "amortized_fine_tuning_lr_5e6"
load_name: "nuplan_womd_fine_tuning1_lr_1"
use_amortized_diffusion: true
use_timestep_weight_loss: false
learning_rate: 5e-6        # ≈ 5e-4 / 3

# Group 설정:
#  - encoder_local(Group A): freeze
#  - encoder_global / decoder 는 기본 lr
freeze_encoder_local: true
lr_scheduler_type: cosine
use_lr_warmup: true
p_sat: 0.
w_int_max: 1.0

resume_local_path_model_path: null
# Stage2는 shell에서 --resume_wandb_model_name latest 로 지정해서 시작
resume_wandb_model_name: latest
resume_model_only: true