# configs/stage2.yaml
name: stage2_test5
past_name: stage1_test5

batch_size: 8 #512
train_epochs: 1 #90 #324               # 234(Stage1) + 90(Stage2)

# Stage2: Stage1보다 1/3 정도 작은 lr에서 시작 → 1/4 근처까지 감소
learning_rate: 1.6667e-4        # ≈ 5e-4 / 3
min_learning_rate: 1.25e-4      # ≈ 5e-4 / 4

# Stage2
center_crop_radius_m: -1.
center_crop_mode: none
do_not_clip: true

# Group 설정:
#  - encoder_local(Group A): freeze
#  - encoder_global / decoder 는 기본 lr
freeze_encoder_local: true
encoder_local_lr_scale: 1.0
encoder_global_lr_scale: 1.0
decoder_lr_scale: 1.0

lr_scheduler_type: cosine
use_lr_warmup: true
warm_up_epoch: 5
p_sat: 0.3

resume_local_path_model_path: null
# Stage2는 shell에서 --resume_wandb_model_name latest 로 지정해서 시작
resume_wandb_model_name: latest
resume_model_only: true
