# configs/stage1.yaml
name: stage1_w_const_0.02_no_8_bit_opt

batch_size: 360 # 512
train_epochs: 234 #234           # 전체 360 중 약 65%

learning_rate: 5.0e-4
min_learning_rate: 1.6667e-4  # Stage1 max lr의 1/3 정도

# Stage1: 작은 장면 + 중심 NPC 기준 100m
center_crop_radius_m: 80.0
center_crop_mode: ego       # 랜덤 NPC 하나 기준

# Group 설정: 전부 같이 학습
freeze_encoder_local: false
encoder_local_lr_scale: 1.0
encoder_global_lr_scale: 1.0
decoder_lr_scale: 1.0

# 스케줄 설정
lr_scheduler_type: cosine
use_lr_warmup: true
warm_up_epoch: 10

# 명시적으로 없음(기본값 사용)
resume_local_path_model_path: null
resume_wandb_model_name: null
