_target_: nuplan_extent.planning.simulation.observation.world_model_agents.WorldModelAgents
_convert_: 'all'

open_loop_detections_types: ["PEDESTRIAN", "BARRIER", "CZONE_SIGN", "TRAFFIC_CONE", "GENERIC_OBJECT"]  # Open-loop detections to include
radius: 100                 # [m] Only agents within this radius around the ego will be simulated.
target_velocity: 10         # Desired velocity in free traffic [m/s]


model_config: world_model # Dictionary key from existing planner model config (e.g. policy_world_model_nar)

checkpoint_path: ???