_target_: diffusion_planner.observation.ego_centric_diffusion_agents.EgoCentricDiffusionAgents
_convert_: 'all'

model_config: # Dictionary key from existing planner model config (e.g. reactive_agents_model)
  _target_: diffusion_planner.observation.diffusion_model.DiffusionPlanner
  config:
    _target_: diffusion_planner.utils.config.Config
    _convert_: "all"
    args_file: /home/user/PycharmProjects/Diffusion-Planner/checkpoints/args.json
  ckpt_path: /home/user/PycharmProjects/Diffusion-Planner/checkpoints/model.pth
  past_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: "all"

    num_poses: 20
    time_horizon: 2

  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.`TrajectorySampling`
    _convert_: "all"

    num_poses: 80
    time_horizon: 8

  feature_builders:
    _target_: diffusion_planner.observation.feature_builder.DataProcessor
    config:
      _target_: diffusion_planner.utils.config.Config
      _convert_: "all"
      args_file: /home/user/PycharmProjects/Diffusion-Planner/checkpoints/args.json
